#!/bin/bash
set -eu

TARGET_ARCH=${DOCKER_TAG//-*}

if [ "$DOCKERFILE_PATH" = "" ]; then
    DOCKERFILE_PATH_ARG=""
else
    DOCKERFILE_PATH_ARG="-f $DOCKERFILE_PATH"
fi

docker build --build-arg TARGET_ARCH=${TARGET_ARCH} ${DOCKERFILE_PATH_ARG} -t $IMAGE_NAME .
